# Generated by Django 5.0 on 2024-03-09 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_productdetails_remove_cartitem_cart_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productdetails',
            name='price',
            field=models.CharField(max_length=20),
        ),
    ]
